Repository Yoshi275/kampongjio, pull requests merged in 2019-07, with the labels that each got.

#33 Modify base json
  src/components/Coordinator/OrderDetails.js
  src/components/Coordinator/OrderList.js
  src/components/Dashboard/InitiatedDetails.js
  src/components/Dashboard/Ongoing.js
  src/components/Dashboard/OngoingDetails.js
  src/components/Dashboard/PreviousDetails.js
  src/components/MainPage/JioList.js
  src/data/AllJios.json
  src/screens/CoordinatorCreateJio.js
  src/screens/JioJoinerOrder.js
Labels: enhancement

#38 feat: Add Login Form design
  src/components/common/Input.js
  src/components/common/NavBar.js
  src/components/common/Spinner.js
  src/components/common/index.js
  src/config.js
  src/screens/JioJoinerOrder.js
  src/screens/LoginForm.js
  src/screens/Router.js
Labels: feature

#39 fix: Remove secureTextEntry from all inputs
  src/components/common/Input.js
  src/screens/Router.js
Labels: bug

#46 feat: Link signup to firebase
  src/screens/LoginForm.js
  src/screens/MainPage.js
  src/screens/Profile.js
  src/screens/SignUp.js
Labels: feature

#48 fix: Filter Jios finally working
  src/App.js
  src/components/Dashboard/DashboardJioDetails.js
  src/components/Dashboard/InitiatedDetails.js
  src/components/Dashboard/OngoingDetails.js
  src/components/Dashboard/PreviousDetails.js
  src/components/MainPage/JioDetails.js
  src/components/MainPage/JioList.js
  src/components/common/NavBar.js
  src/data/AllJios.json
  src/screens/Dashboard.js
  src/screens/JioJoinerOrder.js
  src/screens/LoginForm.js
  src/screens/MainPage.js
  src/screens/Profile.js
Labels: feature

#55 feat: Link coordinatorEditJio to update firebase jio information
  src/components/Coordinator/CoordinatorFullJio.js
  src/components/Coordinator/OrderDetails.js
  src/components/Dashboard/InitiatedDetails.js
  src/components/MainPage/JioDetails.js
  src/screens/CoordinatorEditJio.js
Labels: feature

#56 feat: User jioEdit updates and deletes Firebase
  src/components/Coordinator/OrderDetails.js
  src/components/Dashboard/DashboardJioDetails.js
  src/components/Dashboard/OngoingDetails.js
  src/screens/JioJoinerEditOrder.js
Labels: feature

#57 fix: jioOrderId of all dashboard jios now have the correct firebase id
  src/components/Dashboard/InitiatedDetails.js
  src/components/Dashboard/OngoingDetails.js
  src/components/Dashboard/PreviousDetails.js
Labels: bug

#60 MAJOR fix: Fixed Dashboard to update on change
  src/components/Dashboard/InitiatedDetails.js
  src/components/Dashboard/OngoingDetails.js
  src/components/Dashboard/PreviousDetails.js
  src/screens/CoordinatorEditJio.js
  src/screens/JioJoinerEditOrder.js
  src/screens/JioJoinerOrder.js
Labels: bug

#63 fix: Auto update Coordinator jioStatus + Calc accounts for minOrder
  src/components/Coordinator/CoordinatorFullJio.js
  src/components/Coordinator/OrderDetails.js
  src/screens/Coordinator.js
Labels: bug

#64 feat: Add native image picker
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/kampongjio/MainApplication.java
  android/settings.gradle
  ios/kampongjio.xcodeproj/project.pbxproj
  ios/kampongjio/Info.plist
  package-lock.json
  package.json
  src/components/common/NavBar.js
  src/config.js
  src/resources/icons/image.png
  src/resources/icons/index.js
  src/screens/PickImage.js
  src/screens/Profile.js
  src/screens/Router.js
  src/screens/SignUp.js
  yarn.lock
Labels: feature

#71 fix: Fix compulsory input alert in sign up
  src/screens/SignUp.js
Labels: bug

#72 feat: Upload and see Store image instead of default restaurant icon
  src/components/JioInformation/FullJioDetails.js
  src/components/MainPage/JioDetails.js
  src/screens/CoordinatorCreateJio.js
  src/screens/JioInformation.js
Labels: enhancement

#79 feat: Add Logout logic
  src/screens/Profile.js
Labels: feature
